---
name: Update GitHub Projects Issue Type

on:
  issues:
    types: [opened, edited]

permissions: read-all

env:
  PROJECT_ID: "PVT_kwDOBhbkis4AgtTD"

jobs:
  update-github-projects-issue-type:
    runs-on: ubuntu-latest
    name: Update GitHub Projects Issue Type
    steps:
      - name: Check issue for label
        id: check_labels
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.WOFFENDEN_BOT_GITHUB_TOKEN }}
          script: |
            const issue = context.issue;
            const labels = context.payload.issue.labels.map(label => label.name);

            let type;
            if (labels.includes("bug")) {
              type = "bug";
              fieldOptionId = "4a8bf7e4";
            } else if (labels.includes("feature-request")) {
              type = "feature-request";
              fieldOptionId = "69079d3a";
            } else if (labels.includes("story")) {
              type = "story";
              fieldOptionId = "0a294df2";
            }

            if (type) {
              console.log(`Issue is a ${type}`);
              core.setOutput(
                "type", type,
                "field_option_id", fieldOptionId
              );
            } else {
              console.log("Issue is not a bug, epic, feature-request, or story");
              core.setOutput("type", "undefined");
            }

      - name: Add issue to GitHub Project
        id: add_to_project
        if: steps.check_labels.outputs.type != 'undefined'
        env:
          GITHUB_TOKEN: ${{ secrets.WOFFENDEN_BOT_GITHUB_TOKEN }}
        uses: octokit/graphql-action@ed5ac4718507eeda7aacfe7d78062ca18e9a8768 # v2.3.1
        with:
          query: |
            # Variables have to be snake cased because of https://github.com/octokit/graphql-action/issues/164
            mutation AddProject($project_id: ID!, $content_id: ID!) {
              addProjectV2ItemById(input: { projectId: $project_id, contentId: $content_id }) {
                  item {
                    id
                  }
                }
              }
          variables: |
            project_id: ${{ env.PROJECT_ID }}
            content_id: ${{ github.event.issue.node_id }}